name: pmc_student
description: PMC Student fakultetska aplikacija.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  firebase_auth: ^0.11.1
  cloud_firestore: ^0.12.1

  provider: ^2.0.1+1
  get_it: ^1.0.3+1

dev_dependencies:
  flutter_launcher_icons: ^0.7.2

  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pmc-student-logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"